services:
  - type: web
    name: basketball-coach
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: export PYTHONPATH=$PWD && uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13